[package]
name = "michel-matrix"
version.workspace = true
edition.workspace = true

[dependencies]
matrix-sdk.workspace = true
michel-crypto-store.workspace = true
sqlx.workspace = true
anyhow.workspace = true
tracing.workspace = true
